name: Node testing workflow

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node_v:
        type: string
        required: false
        default: "12.14.1"
env:
  ## Sets environment variable
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_OPTIONS: "--max-old-space-size=4096"
  HUSKY: 0

jobs:
  testing:
    # The type of runner that the job will run on
    # Containers must run in Linux based operating systems
    runs-on: app_backend_ulatest

    container: node:${{ inputs.node_v }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Testing
        uses: totango/shared-github-actions/.github/actions/testing@main
        id: image
        with:
          node_v: ${{ inputs.node_v }}
          npm_token: ${{ secrets.NPM_TOKEN }}
